### ISSUE TITLE
Node not deleted when underlying file is deleted

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/dslink-dart-filesystem#1]
Created a new mount on a directory.  Added a file into the directory.  The file showed up as a node as expected in DGLux.  Deleted the file in the directory.  The file's node remained in DGLux, though its child value nodes disappeared.

Node also remained when the file was deleted through the "Delete" action on the file node itself.  The underlying file was deleted and again the child value nodes with the file's attributes disappeared.

OS is RHEL (uname -a reports: Linux chev-well-1.cisco.com 2.6.32-573.el6.x86_64 #1 SMP Wed Jul 1 18:23:37 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by azenla** [comment]
This should be fixed.
