### ISSUE TITLE
Feature Request: Need a "mv" action

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/dslink-dart-filesystem#2]
Need to be able to move files around on the filesystem.  Essentially, I want to use the filesystem link to watch for files, process them as they appear and move them after they have been processed.  To do that, I need the equivalent of a "mv" command.

**Comment by azenla** [comment]
Ok, I can implement this soon.

**Comment by azenla** [comment]
Implemented in 4633d41.
